version: "3.9"

services:
  backend:
    build: .
    container_name: prismchat-backend
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./app:/app/app
    restart: unless-stopped
